### ISSUE TITLE
ERROR in ./node_modules/y-presence/dist/index.mjs 2:0-99

### ISSUE THREAD

**Issue by kcw2297** [nimeshnayaju/y-presence#1]
Hi, i am currently working on team project using yjs, y-presence and react(typescript).
i got this error and i can't solve it. can i please get some help? thank you in advance.

ERROR in ./node_modules/y-presence/dist/index.mjs 2:0-99
Module not found: Error: Can't resolve 'use-sync-external-store/shim/with-selector' in '/Users/kcw2297/Desktop/Drawing-Duo/node_modules/y-presence/dist'
Did you mean 'with-selector.js'?
BREAKING CHANGE: The request 'use-sync-external-store/shim/with-selector' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by nimeshnayaju** [comment]
Hi, thanks for reporting this issue and sorry I just got a chance to look at it. I have released a new version `0.2.3` that should fix the import issue. Let me know if it works for you.

**Comment by kcw2297** [comment]
Thank you so much for helping!!
