### ISSUE TITLE
Can we implement using WebRTC?

### ISSUE THREAD

**Issue by abhicoditation** [nimeshnayaju/y-presence#2]
Hi,
This may be a very silly and rookie question. Can we implement live cursors using WebRTC instead of WebSocket? 
I tried but looks like only local user state is set and tracked.

**Comment by nimeshnayaju** [comment]
All connection provider for Yjs should be supported. I've forked the `WebSocketProvider` demo and replaced it with `WebRTC` and works as expected. And, not a silly question at all, I've found myself feeling confused about similar things before. Cheers!

WebRTC Demo Link: https://codesandbox.io/s/y-presence-demo-live-cursors-forked-zicojw

**Comment by nimeshnayaju** [comment]
Were you able to run the demo? Let me know if the demo helped.

**Comment by abhicoditation** [comment]
Hi @nimeshnayaju , sorry for late response. 
Yes it helped. I was able to implement it. Thank you !

**Comment by nimeshnayaju** [comment]
Awesome. Good luck on your project!
